# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # This var is needed to work around proxy problems on our Gitlab instance. See https://github.com/fastlane/fastlane/issues/13572
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
    # build the binary
    gym(
      scheme: 'Release',
      export_method: 'app-store',
      export_options: { compileBitcode: false},
      output_directory: './build',
      output_name: 'app-beta'
    )
    # submit to TestFlight
    pilot(
      ipa: './build/app-beta.ipa',
      app_identifier: ENV['APP_IDENTIFIER'],
      skip_submission: false,
      changelog: ENV['CI_COMMIT_MESSAGE'],
      apple_id: ENV['APPLE_ID']
    )
  end
  desc "Promote the beta build to App Store"
  lane :submit_review do
    deliver(
      build_number: ENV['CI_PIPELINE_ID'],
      app_identifier: ENV['APP_IDENTIFIER'],
      app_version: ENV['FLUTTER_APP_VERSION'],
      release_notes: {
        'default' => File.read('./../../changelogs/en-US/release_notes.txt'),
        'en-US' => File.read('./../../changelogs/en-US/release_notes.txt'),
        'de-DE' => File.read('./../../changelogs/de-DE/release_notes.txt')
      },
      submit_for_review: true,
      automatic_release: true,
      force: true, # This skips the HTML report verification
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

   desc "Post updates on Twitter"
   lane :notify_twitter_followers do
     twitter(
       access_token: ENV['TWITTER_ACCESS_TOKEN'],
       access_token_secret: ENV['TWITTER_ACCESS_TOKEN_SECRET'],
       consumer_key: ENV['TWITTER_CONSUMER_API_KEY'],
       consumer_secret: ENV['TWITTER_CONSUMER_API_SECRET_KEY'],
       message: "A new version is available in the App Store: <App Store link>"
     )
   end
end
